### ISSUE TITLE
Ability to get the order of a key

### ISSUE THREAD

**Issue by shashi** [JuliaCollections/OrderedCollections.jl#64]
would be nice!

I want to use these instead of `Dict(vals, 1:length(vals))`...

How would one go about implementing this?

**Comment by timholy** [comment]
You mean, you want the index associated with a key? There's a fundamental conflict between supporting deletion and supporting indexing:
```julia
julia> using OrderedCollections

julia> s = OrderedSet(["one", "two", "three"])
OrderedSet{String} with 3 elements:
  "one"
  "two"
  "three"

julia> delete!(s, "two")
OrderedSet{String} with 2 elements:
  "one"
  "three"
```
Would you want `2` or `3` as the index of `"three"`? If these were like `Array` the answer would be 2, but if these were like `Dict(vals, 1:length(vals))` the answer would be 3. Which one is right?

So far, the choice has been to mimic `Set`, except ordered, and therefore indexing has been avoided.

**Comment by shashi** [comment]
Ahh that's a good point! I don't know what the right answer would be! In my use case I only create a set and never delete, so I didn't think of that! I will close this for now and just use the copy-pasted version which works for us.

**Comment by ilia-kats** [comment]
I realize that this issue is closed, but I think it should be reopened. While there may not be the right way to do this, as long as it's properly documented it should be fine. For my usecase, I'm mostly interested in array indexing, as I'm trying to implement someting akin to Pandas' index for a custom data structure. While I realize that I can just use ht_keyindex on the OrderedDict object wrapped by OrderedSet, I would prefer to avoid depending on implementation details.

Array indexing would also be relatively easy to implement by wrapping ht_keyindex in an exported function that throws KeyError if ht_keyindex returns -1. Happy to do a PR.
