### ISSUE TITLE
Construction from generator may iterate a second time

### ISSUE THREAD

**Issue by yha** [JuliaCollections/OrderedCollections.jl#86]
For example, this:
```
expensive_function(k) = (println(k); k > 2 && error("too large!"))
b = OrderedDict(k => expensive_function(k) for k in 1:3)
```
prints
```
1       
2
3
1
2
3
ERROR: too large!
```
(stack trace omitted)

The constructor shouldn't call my `expensive_function` again on previous elements.
This seems also to affect some (all?) other structures in `DataStructures.jl`.

**Comment by fingolfin** [comment]
So you use a generator expression to compute `expensive_function(k)` for k equal to 1,2,3. But for k=3 you raise an error. So weird things happen...

But all is fine if I adjust your code to use `i > 3`:
```
julia> expensive_function(k) = (println(k); k > 3 && error("too large!"))
expensive_function (generic function with 1 method)

julia> b = OrderedDict(k => expensive_function(k) for k in 1:3)
Base.Generator{UnitRange{Int64}, var"#5#6"}
1
2
3
OrderedDict{Int64, Bool} with 3 entries:
  1 => 0
  2 => 0
  3 => 0
```

Now the second iteration happens because of this method:
```
function OrderedDict(kv)
    try
        dict_with_eltype((K, V) -> OrderedDict{K, V}, kv, eltype(kv))
    catch e
        if isempty(methods(iterate, (typeof(kv),))) ||
            !all(x->isa(x, Union{Tuple,Pair}), kv)
            throw(ArgumentError("OrderedDict(kv): kv needs to be an iterator of tuples or pairs"))
        else
            rethrow(e)
        end
    end
end
```
So if constructing the ordered dict throws an error, it tries to detect if the problem maybe was of a special kind, and if so produces a different error.

Not sure why it does that; `Dict` definitely doesn't do this. I'll make a PR.
